### PR TITLE
Implementation of original (parametric) Combat harmonization

### PR DESCRIPTION
**Pull request by jrasero**
This pull request includes the implementation of the Combat harmonization method, as originally proposed by [Johnson and others in 2007](https://doi.org/10.1093/biostatistics/kxj037). As of the current implementation,  only parametric Bayes frameworks adjustment is covered. I will work on including the non-parametric version shortly. 

There are also a couple of functions testing the new estimator, one using simulated data and other using real data. This data was originally used as a test data in the R package [**SVA**](https://bioconductor.org/packages/release/bioc/html/sva.html) that also implements Combat. We then test that the harmonized data using **Confounds** is the same as that using **SVA**.

### CODE REVIEW

**Comment by jrasero** [comment]
Pradeep, I was not able to make tox tests pass. It seems to be giving me errors because it does not find python3.4 and python3.5. 

The pull-request passed both flake8 and the tests locally, with python3.8.

**Comment by raamana** [comment]
Wonderful! Thanks Javier, this is a fantastic PR I've been looking forward to! :) Let me take a look and make detailed comments. PS: I am currently travelling in India with limited / intermittent internet capabilities, so I might be slower than normal to respond.

**Comment by raamana** [comment]
Hi Javi, sorry for the delay in my reply. I am going through this now, and feel like it helps to have a simple example on how to use this class/method, and as well as some pseudocode on what results we should expect when we employ this method in common use-cases?  Thanks.

**Comment by raamana** [comment]
Hi Javier,

so I've made various small changes we discussed this weeks, and tried to run the test you wrote. and it seems to fail: batch means are still significantly different after applying ComBat(). I pushed the changes to https://github.com/raamana/confounds/tree/combat_param1

can you take a look, and see what's happening? I didn't make any methodological or statistical changes so its unlikely my changes are the issue, but it's possible moving around may have introduced some bugs.

Cheers,
Pradeep

**Comment by jrasero** [comment]
Hi @Pradeep, 

I've found the bug, corrected it locally passing the tests, but github does not allow me to push the changes. It tells me the following:

```
remote: Permission to raamana/confounds.git denied to jrasero.
fatal: unable to access 'https://github.com/raamana/confounds.git/': The requested URL returned error: 403
```

Any idea why this happens?

**Comment by raamana** [comment]
Actually I closed this prematurely @jrasero 😀. We need to expand the test suite to cover many key aspects including the separation between train and test sets and few other checks on gaussianity etc

**Pull request merged**
